apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-postgresql
  namespace: {{ .Release.Namespace }}
spec:
  serviceName: {{ .Release.Name }}-postgresql
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-postgresql
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-postgresql
    spec:
      containers:
        - name: postgresql
          image: postgres:16.2-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: courierdb
            - name: POSTGRES_USER
              value: courier_user
            - name: POSTGRES_PASSWORD
              value: courier_pass_local
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          args:
            - "-c"
            - "max_connections=100"
            - "-c"
            - "shared_buffers=128MB"
          resources:
            requests:
              cpu: 150m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "courier_user", "-d", "courierdb"]
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 6
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: hostpath
        resources:
          requests:
            storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-postgresql
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{ .Release.Name }}-postgresql
  ports:
    - port: 5432
      targetPort: 5432
  type: ClusterIP
