apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-timescaledb
  namespace: {{ .Release.Namespace }}
spec:
  serviceName: {{ .Release.Name }}-timescaledb
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-timescaledb
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-timescaledb
    spec:
      containers:
        - name: timescaledb
          image: timescale/timescaledb:2.14.2-pg16
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: gpsdb
            - name: POSTGRES_USER
              value: gps_user
            - name: POSTGRES_PASSWORD
              value: gps_pass_local
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          resources:
            requests:
              cpu: 150m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "gps_user", "-d", "gpsdb"]
            initialDelaySeconds: 15
            periodSeconds: 5
            failureThreshold: 6
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: hostpath
        resources:
          requests:
            storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-timescaledb
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{ .Release.Name }}-timescaledb
  ports:
    - port: 5433
      targetPort: 5432
  type: ClusterIP
