apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: deli-ingress
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/proxy-body-size: "20m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "Upgrade";
spec:
  rules:
    - host: api.courier.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: deli-api-gateway
                port:
                  number: 80

    - host: ws.courier.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: deli-api-gateway
                port:
                  number: 81

    - host: minio.courier.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: deli-platform-minio
                port:
                  number: 9001
