apiVersion: v1
kind: Secret
metadata:
  name: platform-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/part-of: deli-platform
type: Opaque
stringData:
  POSTGRES_USER:     "courier_user"
  POSTGRES_PASSWORD: {{ .Values.global.postgresPassword | quote }}
  TIMESCALE_USER:    "gps_user"
  TIMESCALE_PASSWORD: {{ .Values.global.timescalePassword | quote }}
  REDIS_PASSWORD:    {{ .Values.global.redisPassword | quote }}
  JWT_SECRET:        {{ .Values.global.jwtSecret | quote }}
  S3_ACCESS_KEY:     {{ .Values.global.s3AccessKey | quote }}
  S3_SECRET_KEY:     {{ .Values.global.s3SecretKey | quote }}
  MAPS_API_KEY:      {{ .Values.global.mapsApiKey | quote }}
