apiVersion: v2
name: notification-service
description: Helm chart for the Deli notification-service
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: deli-common
    version: "0.1.0"
    repository: "file://../deli-common"
